<?php

/**
 * Implements hook_menu().
 */
function media_fotoweb_menu() {
  $items = array();

  $items['media-fotoweb/add/asset'] = array(
    'page callback' => '_media_fotoweb_add_asset_from_fotoweb',
    'access arguments' => array('create files'),
    'type' => MENU_CALLBACK,
    'file' => 'media_fotoweb.asset.inc',
    'file path' => drupal_get_path('module', 'media_fotoweb') . '/includes',
  );

  return $items;
}

/**
 * Implements hook_stream_wrappers().
 */
function media_fotoweb_stream_wrappers() {
  return array(
    'fotoweb' => array(
      'name' => t('Fotoweb assets'),
      'class' => 'FotowebStreamWrapper',
      'description' => t('Assets provided by Fotoweb.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_file_mimetype_mapping_alter().
 */
function media_fotoweb_file_mimetype_mapping_alter(&$mapping) {
  $mapping['mimetypes'][] = 'image/fotoweb';
}

/**
 * Implements hook_file_default_types_alter().
 */
function media_fotoweb_file_default_types_alter(&$types) {
  $types['image']->mimetypes[] = 'image/fotoweb';
}

/**
 * Implements hook_media_browser_plugin_info().
 */
function media_fotoweb_media_browser_plugin_info() {
  $info = array(
    'fotoweb' => array(
      'title' => t('Fotoweb search'),
      'class' => 'FotowebBrowser',
      'weight' => 50,
    ),
  );
  return $info;
}
