<?php

/**
 * @file
 * Contains media_fotoweb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function media_fotoweb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the media_fotoweb module.
    case 'help.page.media_fotoweb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates media with the digital asset management from fotoware.com') . '</p>';
      return $output;

    default:
  }
}
