media_fotoweb.settings:
  type: config_object
  label: 'Media Fotoweb Settings'
  mapping:
    server:
      type: string
      label: 'Fotoweb server'
    full_api_key:
      type: string
      label: 'Full API Key'
    selection_widget_use_sso:
      type: boolean
      label: 'Use SSO for the asset selection widget?'
    encryption_secret:
      type: string
      label: 'Encryption secret'
    sso_user_field:
      type: string
      label: 'SSO user field'
    selection_widget_height:
      type: integer
      label: 'Selection Widget Height'
    file_storage_type:
      type: string
      label: 'File storage type'
    local_file_size_threshold:
      type: string
      label: 'Local file size threshold'
    asset_update_type:
      type: string
      label: 'Asset update type'
    rendition_service:
      type: string
      label: 'Fotoweb rendition service'
