<?php

/**
 * Class FotowebArchives represents Fotoweb archives.
 *
 * Archives are collections which represent physical folders containing
 * physical files. Every FotoWeb site can have zero or more archives, which can
 * be set up using the FotoWeb configuration interface.
 *
 * @see https://learn.fotoware.com/02_FotoWeb_8.0/Developing_with_the_FotoWeb_API/01_The_FotoWeb_RESTful_API/06_Archives
 */
class FotowebArchives extends FotowebCollectionList {

}
